In [1]:
import warnings
warnings.filterwarnings('ignore')

In [3]:
import pandas as pd
import numpy as np
iris_data = pd.read_csv('iris_data.csv')  ## 정답 데이터

In [11]:
iris_data.head()  ## 독립변수는 4개, 종속변수는 species

sepal_length  sepal_width  petal_length  petal_width  species
0           7.0          3.2           4.7          1.4        0
1           6.4          3.2           4.5          1.5        0
2           6.9          3.1           4.9          1.5        0
3           5.5          2.3           4.0          1.3        0
4           6.5          2.8           4.6          1.5        0

In [13]:
## 독립변수 데이터와 종속변수 데이터를 다른 변수에 저장해야 함
iris_features = iris_data.drop(columns=['species'])  # 종속변수를 제외하고 저장 (독립변수)
iris_labels = iris_data['species']  # 종속변수 저장

In [15]:
iris_features.shape

(100, 4)

In [6]:
iris_labels 

0     0
1     0
2     0
3     0
4     0
     ..
95    1
96    1
97    1
98    1
99    1
Name: species, Length: 100, dtype: int64

In [40]:
# 정답데이터를 학습데이터와 평가 데이터로 분할
from sklearn.model_selection import train_test_split   ## train_test_split 함수 사용
X_train, X_test, y_train, y_test = train_test_split(iris_features, iris_labels, test_size = 0.3)
# test_size는 전체 정답데이터 중 몇 퍼센트를 평가 데이터로 사용할지 결정 (여기서는 30%)
# x_train, y_train은 각각 독립변수와 종속변수에 대한 학습데이터
# x_test, y_test는 각각 독립변수와 종속변수에 대한 평가데이터

In [42]:
from sklearn.linear_model import LogisticRegression   ## 로지스틱 회귀모형을 통해 학습 수행

In [44]:
lr_base = LogisticRegression(penalty=None)    ## 객체를 생성
# penalty: 규제화 L1과 L2 중 뭘 사용하고 싶은지 결정 (원하는 방식을 써넣으면 됨. 여기서는 None)
# 범주형이므로 교차 엔트로피

In [46]:
lr_base.fit(X_train, y_train)
## fit이라는 함수로 학습 (독립변수 학습데이터, 종속변수 학습 데이터)

LogisticRegression(penalty=None)

In [60]:
lr_base.coef_    ## 로지스틱 회귀모형의 파라미터 최적값 (떄마다 조금씩 다를 수 있음)
## P(y=1)의 확률을 나타내는 로지스틱 모형의 파라미터 최적값들을 결정함
## 즉 y=1, 붓꽃이 verginica일 확률은 첫번째, 두번째 파라미터와 음의 관계를 가짐
## 세번째 독립변수가 가장 큰 영향을 미침

array([[-397.4545509 , -333.37250591,  595.47795675,  445.56965012]])

In [52]:
lr_base.intercept_    ## b_0: 절편 

array([-256.31566037])

# 평가

In [56]:
len(y_test)   ## 종속변수 평가데이터 개수

30

In [64]:
lr_base.score(X_test, y_test)   ## 평가 지표 (1에 가까울수록 적절한 모형이라는 뜻)
## 약 97% 정도 정확하게 예측함

0.9666666666666667

In [66]:
y_predictions = lr_base.predict(X_test)

In [68]:
lr_base.predict_proba(X_test)

array([[0.00000000e+000, 1.00000000e+000],
       [0.00000000e+000, 1.00000000e+000],
       [1.00000000e+000, 7.55556525e-132],
       [0.00000000e+000, 1.00000000e+000],
       [0.00000000e+000, 1.00000000e+000],
       [0.00000000e+000, 1.00000000e+000],
       [1.48103751e-013, 1.00000000e+000],
       [0.00000000e+000, 1.00000000e+000],
       [1.00000000e+000, 2.29989300e-188],
       [0.00000000e+000, 1.00000000e+000],
       [0.00000000e+000, 1.00000000e+000],
       [1.00000000e+000, 5.14588563e-166],
       [0.00000000e+000, 1.00000000e+000],
       [1.00000000e+000, 4.84103489e-143],
       [1.00000000e+000, 1.45377432e-113],
       [0.00000000e+000, 1.00000000e+000],
       [0.00000000e+000, 1.00000000e+000],
       [1.00000000e+000, 1.99599244e-194],
       [1.00000000e+000, 4.93541269e-273],
       [1.00000000e+000, 1.56964306e-159],
       [1.00000000e+000, 2.81299704e-238],
       [0.00000000e+000, 1.00000000e+000],
       [1.00000000e+000, 2.36215609e-137],
       [0.0

In [34]:
y_predictions

array([0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1,
       0, 0, 1, 1, 0, 1, 0, 0], dtype=int64)

In [35]:
print(y_test.to_list())

[0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0]


In [72]:
from sklearn.metrics import accuracy_score  # 평가지표 중 정확도
y_predictions = lr_base.predict(X_test)
accuracy_score(y_test, y_predictions)

0.9666666666666667

## Regularization (규제화) 적용하기

In [33]:
lr_p1 = LogisticRegression(C=0.1, penalty='l1', solver = 'saga', max_iter=1000) 

C = Inverse of regularization strength, 즉 C 값이 작을수록 penalty를 많이 준다는 것입니다.<br>
solver => 어떠한 방법을 사용해서 optimal한 parameter의 방법을 찾는지에 대한것

In [34]:
lr_p1.fit(X_train, y_train)

LogisticRegression(C=0.1, max_iter=1000, penalty='l1', solver='saga')

In [35]:
lr_p1.coef_

array([[0.        , 0.        , 1.36570487, 0.        ]])

In [31]:
lr_p1.coef_

array([[-1.4591589 , -1.06923503,  2.91862835,  3.72530786]])

In [32]:
lr_p1.score(X_test, y_test)

0.9333333333333333

In [42]:
lr_p2 = LogisticRegression(C=1, penalty='l2', solver='saga', max_iter=1000) 

In [43]:
lr_p2.fit(X_train, y_train)

LogisticRegression(C=1, max_iter=1000, solver='saga')

In [44]:
lr_p2.score(X_test, y_test)

0.9666666666666667

In [45]:
lr_p2.coef_

array([[-0.7534406 , -0.61477011,  2.34091379,  2.10356513]])

## Check model performance

In [46]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, y_predictions)

array([[17,  1],
       [ 0, 12]], dtype=int64)

In [47]:
from sklearn.metrics import classification_report
print(classification_report(y_test, y_predictions))

              precision    recall  f1-score   support

           0       1.00      0.94      0.97        18
           1       0.92      1.00      0.96        12

    accuracy                           0.97        30
   macro avg       0.96      0.97      0.97        30
weighted avg       0.97      0.97      0.97        30

